services:
  nvblox:
    image: nvblox:base
    container_name: nvblox
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ../../../src:/root/nvblox_ws/src
      - /tmp/.X11-unix:/tm  p/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: host
    privileged: true
    command: tail -f /dev/null
